### ISSUE TITLE
Template action with ID 'slack:sendMessage:webhook' is not registered

### ISSUE THREAD

**Issue by chauvm** [arhill05/backstage-plugin-scaffolder-backend-module-slack#10]
I got this error `Template action with ID 'slack:sendMessage:webhook' is not registered` when I created an action from a template similar to your example.

```
# my template
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: slack-message-demo
  title: My Slack message demo
  description: Send a message via Slack
spec:
  owner: someowner
  type: service

  steps:
    # this step is an example of using the webhook action
    - id: send-slack-message
      name: Send slack message via Slack webhook
      action: slack:sendMessage:webhook
      input:
        message: "Hello!"
```
<img width="1487" alt="template_action_error" src="https://github.com/user-attachments/assets/c02191c7-f531-4f1d-af75-2aadd5bb47e1">

Here's what I have in `apps/backstage/packages/backend/src/index.ts`:
```
import sendSlackMessageModule from '@mdude2314/backstage-plugin-scaffolder-backend-module-slack';
...
backend.add(sendSlackMessageModule());
```

I noticed there's no slack actions under installed actions via `<my-backstage-url>/create/actions`. Am I missing some steps to register this action?
